<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <Configurations>Debug;Release;Mudblazor;FastUI</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>CNInnovation.Codebreaker.Services</PackageId>
    <Authors>CN innovation</Authors>
    <Company>CN innovation</Company>
    <PackageDescription>
      Codebreaker client library to access the Game API and the Live Services API with GameClient and LiveClient
    </PackageDescription>
    <RepositoryUrl>https://github.com/CNinnovation/codebreakerpackages</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CNInnovation.Codebreaker.Shared" Version="2.0.1-beta.1.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.66.1" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.66.1" />
  </ItemGroup>

</Project>
